#!/usr/bin/env python3
"""Write the run log's per-configuration record from the evidence itself.

Owner: Part 1 -- Yeo Kai Yuan (technical core).

docs/run-log.md asks for one dated entry per configuration. After an unattended
campaign the facts of each entry are all in the run directories already, so this
script reads them rather than having someone retype them: every metadata.json
under results/runs/ and results/accuracy/ (real mode only), the reconciliation
summary written by scripts/run_analysis.sh, and the campaign log. It prints a
Markdown section to paste into docs/run-log.md. It measures nothing.

Usage:
    .venv/bin/python scripts/campaign_record.py [--results results] [--analysis analysis/output]
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def ts(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def hhmm(value: datetime | None) -> str:
    return value.strftime("%Y-%m-%d %H:%M") if value else "?"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--results", default="results")
    parser.add_argument("--analysis", default="analysis/output")
    args = parser.parse_args()
    results, analysis = REPO / args.results, REPO / args.analysis

    reconcile: dict[str, str] = {}
    summary = analysis / "reconcile" / "SUMMARY.md"
    if summary.is_file():
        for match in re.finditer(r"^\| `([^`]+)` \| (\d+) \|", summary.read_text(encoding="utf-8"), re.M):
            reconcile[match.group(1)] = "PASS" if match.group(2) == "0" else f"FAIL (exit {match.group(2)})"

    configs: dict[tuple, list[dict]] = {}
    for meta_path in sorted((results / "runs").glob("*/metadata.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        if meta.get("mode") != "real":
            continue
        rate = "ramp" if meta.get("plan") == "stress_ramp" else f"{meta.get('rate_per_min'):g}/min"
        if meta.get("plan") == "stress_ramp":
            start = re.search(r"ramp_start_per_min=(\d+)", meta.get("notes", ""))
            rate = f"ramp from {start.group(1)}/min" if start else "ramp"
        configs.setdefault((meta["model_tag"], meta["plan"], rate), []).append({**meta, "_dir": meta_path.parent.name})

    print("## Campaign record (generated by `scripts/campaign_record.py` from the run directories)\n")
    print("One row per configuration. Every run is real mode, frozen at the commit in its `freeze.json`, posted to")
    print("`service_url` from the host in `load_generator_host_info.hostname`; reconciliation is `analysis/reconcile.py`")
    print("via `scripts/run_analysis.sh`. Verdict for every row: **reportable** unless the row says otherwise.\n")
    print("| Model | Plan | Rate | Runs | Started (UTC) | Wall-clock | Load generator → service | Reconciliation |")
    print("|---|---|---|---|---|---|---|---|")
    for (model, plan, rate), runs in sorted(configs.items(), key=lambda kv: min(r["started_at_utc"] for r in kv[1])):
        starts = [ts(r["started_at_utc"]) for r in runs]
        ends = [ts(r["ended_at_utc"]) for r in runs]
        wall = (max(e for e in ends if e) - min(s for s in starts if s)).total_seconds() / 60
        hosts = sorted({(r.get("load_generator_host_info") or {}).get("hostname", "?") for r in runs})
        urls = sorted({r.get("service_url", "?") for r in runs})
        rec = sorted({reconcile.get(r["_dir"], "not run") for r in runs})
        dirs = ", ".join(f"`{r['_dir']}`" for r in sorted(runs, key=lambda r: r["run_index"]))
        print(f"| `{model}` | `{plan}` | {rate} | {len(runs)} | {hhmm(min(starts))} | {wall:.0f} min "
              f"(last run ends {hhmm(max(ends))}) | {', '.join(hosts)} → {', '.join(urls)} | {', '.join(rec)} |")
    print()
    print("Run directories, per configuration:\n")
    for (model, plan, rate), runs in sorted(configs.items(), key=lambda kv: min(r["started_at_utc"] for r in kv[1])):
        dirs = ", ".join(f"`{r['_dir']}`" for r in sorted(runs, key=lambda r: r["run_index"]))
        print(f"- `{model}` `{plan}` {rate}: {dirs}")
    print()
    print("Accuracy runs (one serial pass of the 200 golden tickets per model):\n")
    print("| Model | Run directory | Started (UTC) | Wall-clock | Posted | Load generator → service |")
    print("|---|---|---|---|---|---|")
    for meta_path in sorted((results / "accuracy").glob("*/metadata.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        if meta.get("mode") != "real":
            continue
        start, end = ts(meta["started_at_utc"]), ts(meta["ended_at_utc"])
        posted = re.search(r"posted=(\d+)", meta.get("notes", ""))
        print(f"| `{meta['model_tag']}` | `{meta_path.parent.name}` | {hhmm(start)} | {(end - start).total_seconds():.0f} s "
              f"| {posted.group(1) if posted else '?'} | {(meta.get('load_generator_host_info') or {}).get('hostname', '?')} → "
              f"{meta.get('service_url', '?')} |")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
